server:
  port: 8082

simulator:
  enabled: true
  interval-ms: 600000
  target-url: http://localhost:8081/api/v1/collect/device-data
  devices:
    - device-uuid: "demo-sim-001"
      gas-type: CH4
      concentration:
        min: 0.0
        max: 5.0
      battery:
        min: 3.2
        max: 4.2
      temperature:
        min: 15.0
        max: 35.0
      humidity:
        min: 30.0
        max: 70.0
    - device-uuid: "demo-sim-002"
      gas-type: H2S
      concentration:
        min: 0.0
        max: 8.0
      battery:
        min: 3.0
        max: 4.0
      temperature:
        min: 20.0
        max: 40.0
      humidity:
        min: 25.0
        max: 65.0
    - device-uuid: "demo-sim-003"
      gas-type: CO
      concentration:
        min: 0.0
        max: 45.0
      battery:
        min: 3.1
        max: 4.1
      temperature:
        min: 25.0
        max: 45.0
      humidity:
        min: 35.0
        max: 60.0

logging:
  level:
    com.niit.simulator: DEBUG
